### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by ParaImage** [animikhaich/single-object-background-subtractor#2]
Can you upload pre-trained model, please?

**Comment by animikhaich** [comment]
This is a very old project, hence I am not entirely sure if I have the pre-trained model or not. However, I did manage to find this, which seems to be the trained weights: https://drive.google.com/file/d/1muyXsZTxx9kz8RwnwOt2-DhV8tu0APmO/view?usp=share_link

Feel free to try it out.
